### ISSUE TITLE
Please add a locator to password input for LoginPage

### ISSUE THREAD

**Issue by meow-meow-cpu** [meow-meow-cpu/Helioteca#1]
@milyjjang 
[    @FindBy()                       //Emily](https://github.com/meow-meow-cpu/Helioteca/blob/1f808d8acf45a8501cb7de36cfcce04e343da9ce/src/test/java/com/helioteca/pages/LoginPage.java#L20)

**Comment by milyjjang** [comment]
@meow-meow-cpu password locator added and pushed into my branch
